// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package xtdb_protos;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xtdb_protos.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code xtdb_protos.Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xtdb_protos.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xtdb_protos.Service.internal_static_xtdb_protos_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xtdb_protos.Service.internal_static_xtdb_protos_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xtdb_protos.Service.Empty.class, xtdb_protos.Service.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xtdb_protos.Service.Empty)) {
        return super.equals(obj);
      }
      xtdb_protos.Service.Empty other = (xtdb_protos.Service.Empty) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xtdb_protos.Service.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xtdb_protos.Service.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xtdb_protos.Service.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xtdb_protos.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xtdb_protos.Empty)
        xtdb_protos.Service.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xtdb_protos.Service.internal_static_xtdb_protos_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xtdb_protos.Service.internal_static_xtdb_protos_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xtdb_protos.Service.Empty.class, xtdb_protos.Service.Empty.Builder.class);
      }

      // Construct using xtdb_protos.Service.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xtdb_protos.Service.internal_static_xtdb_protos_Empty_descriptor;
      }

      @java.lang.Override
      public xtdb_protos.Service.Empty getDefaultInstanceForType() {
        return xtdb_protos.Service.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public xtdb_protos.Service.Empty build() {
        xtdb_protos.Service.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xtdb_protos.Service.Empty buildPartial() {
        xtdb_protos.Service.Empty result = new xtdb_protos.Service.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xtdb_protos.Service.Empty) {
          return mergeFrom((xtdb_protos.Service.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xtdb_protos.Service.Empty other) {
        if (other == xtdb_protos.Service.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xtdb_protos.Service.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xtdb_protos.Service.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xtdb_protos.Empty)
    }

    // @@protoc_insertion_point(class_scope:xtdb_protos.Empty)
    private static final xtdb_protos.Service.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xtdb_protos.Service.Empty();
    }

    public static xtdb_protos.Service.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xtdb_protos.Service.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xtdb_protos.StatusResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>int32 index_version = 2;</code>
     * @return The indexVersion.
     */
    int getIndexVersion();

    /**
     * <code>string kv_store = 3;</code>
     * @return The kvStore.
     */
    java.lang.String getKvStore();
    /**
     * <code>string kv_store = 3;</code>
     * @return The bytes for kvStore.
     */
    com.google.protobuf.ByteString
        getKvStoreBytes();

    /**
     * <code>int32 estimate_num_keys = 4;</code>
     * @return The estimateNumKeys.
     */
    int getEstimateNumKeys();

    /**
     * <code>int64 size = 5;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <code>optional string revision = 6;</code>
     * @return Whether the revision field is set.
     */
    boolean hasRevision();
    /**
     * <code>optional string revision = 6;</code>
     * @return The revision.
     */
    java.lang.String getRevision();
    /**
     * <code>optional string revision = 6;</code>
     * @return The bytes for revision.
     */
    com.google.protobuf.ByteString
        getRevisionBytes();

    /**
     * <code>optional string consumer_state = 7;</code>
     * @return Whether the consumerState field is set.
     */
    boolean hasConsumerState();
    /**
     * <code>optional string consumer_state = 7;</code>
     * @return The consumerState.
     */
    java.lang.String getConsumerState();
    /**
     * <code>optional string consumer_state = 7;</code>
     * @return The bytes for consumerState.
     */
    com.google.protobuf.ByteString
        getConsumerStateBytes();
  }
  /**
   * Protobuf type {@code xtdb_protos.StatusResponse}
   */
  public static final class StatusResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xtdb_protos.StatusResponse)
      StatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StatusResponse.newBuilder() to construct.
    private StatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatusResponse() {
      version_ = "";
      kvStore_ = "";
      revision_ = "";
      consumerState_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StatusResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StatusResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 16: {

              indexVersion_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              kvStore_ = s;
              break;
            }
            case 32: {

              estimateNumKeys_ = input.readInt32();
              break;
            }
            case 40: {

              size_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              revision_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              consumerState_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xtdb_protos.Service.internal_static_xtdb_protos_StatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xtdb_protos.Service.internal_static_xtdb_protos_StatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xtdb_protos.Service.StatusResponse.class, xtdb_protos.Service.StatusResponse.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_VERSION_FIELD_NUMBER = 2;
    private int indexVersion_;
    /**
     * <code>int32 index_version = 2;</code>
     * @return The indexVersion.
     */
    @java.lang.Override
    public int getIndexVersion() {
      return indexVersion_;
    }

    public static final int KV_STORE_FIELD_NUMBER = 3;
    private volatile java.lang.Object kvStore_;
    /**
     * <code>string kv_store = 3;</code>
     * @return The kvStore.
     */
    @java.lang.Override
    public java.lang.String getKvStore() {
      java.lang.Object ref = kvStore_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kvStore_ = s;
        return s;
      }
    }
    /**
     * <code>string kv_store = 3;</code>
     * @return The bytes for kvStore.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKvStoreBytes() {
      java.lang.Object ref = kvStore_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kvStore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ESTIMATE_NUM_KEYS_FIELD_NUMBER = 4;
    private int estimateNumKeys_;
    /**
     * <code>int32 estimate_num_keys = 4;</code>
     * @return The estimateNumKeys.
     */
    @java.lang.Override
    public int getEstimateNumKeys() {
      return estimateNumKeys_;
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private long size_;
    /**
     * <code>int64 size = 5;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    public static final int REVISION_FIELD_NUMBER = 6;
    private volatile java.lang.Object revision_;
    /**
     * <code>optional string revision = 6;</code>
     * @return Whether the revision field is set.
     */
    @java.lang.Override
    public boolean hasRevision() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string revision = 6;</code>
     * @return The revision.
     */
    @java.lang.Override
    public java.lang.String getRevision() {
      java.lang.Object ref = revision_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        revision_ = s;
        return s;
      }
    }
    /**
     * <code>optional string revision = 6;</code>
     * @return The bytes for revision.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRevisionBytes() {
      java.lang.Object ref = revision_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revision_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUMER_STATE_FIELD_NUMBER = 7;
    private volatile java.lang.Object consumerState_;
    /**
     * <code>optional string consumer_state = 7;</code>
     * @return Whether the consumerState field is set.
     */
    @java.lang.Override
    public boolean hasConsumerState() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string consumer_state = 7;</code>
     * @return The consumerState.
     */
    @java.lang.Override
    public java.lang.String getConsumerState() {
      java.lang.Object ref = consumerState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumerState_ = s;
        return s;
      }
    }
    /**
     * <code>optional string consumer_state = 7;</code>
     * @return The bytes for consumerState.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConsumerStateBytes() {
      java.lang.Object ref = consumerState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (indexVersion_ != 0) {
        output.writeInt32(2, indexVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kvStore_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, kvStore_);
      }
      if (estimateNumKeys_ != 0) {
        output.writeInt32(4, estimateNumKeys_);
      }
      if (size_ != 0L) {
        output.writeInt64(5, size_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, revision_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, consumerState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (indexVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, indexVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kvStore_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, kvStore_);
      }
      if (estimateNumKeys_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, estimateNumKeys_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, size_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, revision_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, consumerState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xtdb_protos.Service.StatusResponse)) {
        return super.equals(obj);
      }
      xtdb_protos.Service.StatusResponse other = (xtdb_protos.Service.StatusResponse) obj;

      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getIndexVersion()
          != other.getIndexVersion()) return false;
      if (!getKvStore()
          .equals(other.getKvStore())) return false;
      if (getEstimateNumKeys()
          != other.getEstimateNumKeys()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (hasRevision() != other.hasRevision()) return false;
      if (hasRevision()) {
        if (!getRevision()
            .equals(other.getRevision())) return false;
      }
      if (hasConsumerState() != other.hasConsumerState()) return false;
      if (hasConsumerState()) {
        if (!getConsumerState()
            .equals(other.getConsumerState())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + INDEX_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getIndexVersion();
      hash = (37 * hash) + KV_STORE_FIELD_NUMBER;
      hash = (53 * hash) + getKvStore().hashCode();
      hash = (37 * hash) + ESTIMATE_NUM_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getEstimateNumKeys();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      if (hasRevision()) {
        hash = (37 * hash) + REVISION_FIELD_NUMBER;
        hash = (53 * hash) + getRevision().hashCode();
      }
      if (hasConsumerState()) {
        hash = (37 * hash) + CONSUMER_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getConsumerState().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xtdb_protos.Service.StatusResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xtdb_protos.Service.StatusResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.StatusResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xtdb_protos.Service.StatusResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xtdb_protos.Service.StatusResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xtdb_protos.StatusResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xtdb_protos.StatusResponse)
        xtdb_protos.Service.StatusResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xtdb_protos.Service.internal_static_xtdb_protos_StatusResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xtdb_protos.Service.internal_static_xtdb_protos_StatusResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xtdb_protos.Service.StatusResponse.class, xtdb_protos.Service.StatusResponse.Builder.class);
      }

      // Construct using xtdb_protos.Service.StatusResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = "";

        indexVersion_ = 0;

        kvStore_ = "";

        estimateNumKeys_ = 0;

        size_ = 0L;

        revision_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        consumerState_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xtdb_protos.Service.internal_static_xtdb_protos_StatusResponse_descriptor;
      }

      @java.lang.Override
      public xtdb_protos.Service.StatusResponse getDefaultInstanceForType() {
        return xtdb_protos.Service.StatusResponse.getDefaultInstance();
      }

      @java.lang.Override
      public xtdb_protos.Service.StatusResponse build() {
        xtdb_protos.Service.StatusResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xtdb_protos.Service.StatusResponse buildPartial() {
        xtdb_protos.Service.StatusResponse result = new xtdb_protos.Service.StatusResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.version_ = version_;
        result.indexVersion_ = indexVersion_;
        result.kvStore_ = kvStore_;
        result.estimateNumKeys_ = estimateNumKeys_;
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.revision_ = revision_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.consumerState_ = consumerState_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xtdb_protos.Service.StatusResponse) {
          return mergeFrom((xtdb_protos.Service.StatusResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xtdb_protos.Service.StatusResponse other) {
        if (other == xtdb_protos.Service.StatusResponse.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getIndexVersion() != 0) {
          setIndexVersion(other.getIndexVersion());
        }
        if (!other.getKvStore().isEmpty()) {
          kvStore_ = other.kvStore_;
          onChanged();
        }
        if (other.getEstimateNumKeys() != 0) {
          setEstimateNumKeys(other.getEstimateNumKeys());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (other.hasRevision()) {
          bitField0_ |= 0x00000001;
          revision_ = other.revision_;
          onChanged();
        }
        if (other.hasConsumerState()) {
          bitField0_ |= 0x00000002;
          consumerState_ = other.consumerState_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xtdb_protos.Service.StatusResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xtdb_protos.Service.StatusResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 1;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int indexVersion_ ;
      /**
       * <code>int32 index_version = 2;</code>
       * @return The indexVersion.
       */
      @java.lang.Override
      public int getIndexVersion() {
        return indexVersion_;
      }
      /**
       * <code>int32 index_version = 2;</code>
       * @param value The indexVersion to set.
       * @return This builder for chaining.
       */
      public Builder setIndexVersion(int value) {
        
        indexVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndexVersion() {
        
        indexVersion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object kvStore_ = "";
      /**
       * <code>string kv_store = 3;</code>
       * @return The kvStore.
       */
      public java.lang.String getKvStore() {
        java.lang.Object ref = kvStore_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kvStore_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string kv_store = 3;</code>
       * @return The bytes for kvStore.
       */
      public com.google.protobuf.ByteString
          getKvStoreBytes() {
        java.lang.Object ref = kvStore_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kvStore_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string kv_store = 3;</code>
       * @param value The kvStore to set.
       * @return This builder for chaining.
       */
      public Builder setKvStore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kvStore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string kv_store = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKvStore() {
        
        kvStore_ = getDefaultInstance().getKvStore();
        onChanged();
        return this;
      }
      /**
       * <code>string kv_store = 3;</code>
       * @param value The bytes for kvStore to set.
       * @return This builder for chaining.
       */
      public Builder setKvStoreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kvStore_ = value;
        onChanged();
        return this;
      }

      private int estimateNumKeys_ ;
      /**
       * <code>int32 estimate_num_keys = 4;</code>
       * @return The estimateNumKeys.
       */
      @java.lang.Override
      public int getEstimateNumKeys() {
        return estimateNumKeys_;
      }
      /**
       * <code>int32 estimate_num_keys = 4;</code>
       * @param value The estimateNumKeys to set.
       * @return This builder for chaining.
       */
      public Builder setEstimateNumKeys(int value) {
        
        estimateNumKeys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 estimate_num_keys = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEstimateNumKeys() {
        
        estimateNumKeys_ = 0;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 5;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 5;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object revision_ = "";
      /**
       * <code>optional string revision = 6;</code>
       * @return Whether the revision field is set.
       */
      public boolean hasRevision() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string revision = 6;</code>
       * @return The revision.
       */
      public java.lang.String getRevision() {
        java.lang.Object ref = revision_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          revision_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string revision = 6;</code>
       * @return The bytes for revision.
       */
      public com.google.protobuf.ByteString
          getRevisionBytes() {
        java.lang.Object ref = revision_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          revision_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string revision = 6;</code>
       * @param value The revision to set.
       * @return This builder for chaining.
       */
      public Builder setRevision(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        revision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string revision = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRevision() {
        bitField0_ = (bitField0_ & ~0x00000001);
        revision_ = getDefaultInstance().getRevision();
        onChanged();
        return this;
      }
      /**
       * <code>optional string revision = 6;</code>
       * @param value The bytes for revision to set.
       * @return This builder for chaining.
       */
      public Builder setRevisionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        revision_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object consumerState_ = "";
      /**
       * <code>optional string consumer_state = 7;</code>
       * @return Whether the consumerState field is set.
       */
      public boolean hasConsumerState() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string consumer_state = 7;</code>
       * @return The consumerState.
       */
      public java.lang.String getConsumerState() {
        java.lang.Object ref = consumerState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          consumerState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string consumer_state = 7;</code>
       * @return The bytes for consumerState.
       */
      public com.google.protobuf.ByteString
          getConsumerStateBytes() {
        java.lang.Object ref = consumerState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumerState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string consumer_state = 7;</code>
       * @param value The consumerState to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        consumerState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string consumer_state = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumerState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        consumerState_ = getDefaultInstance().getConsumerState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string consumer_state = 7;</code>
       * @param value The bytes for consumerState to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        consumerState_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xtdb_protos.StatusResponse)
    }

    // @@protoc_insertion_point(class_scope:xtdb_protos.StatusResponse)
    private static final xtdb_protos.Service.StatusResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xtdb_protos.Service.StatusResponse();
    }

    public static xtdb_protos.Service.StatusResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatusResponse>
        PARSER = new com.google.protobuf.AbstractParser<StatusResponse>() {
      @java.lang.Override
      public StatusResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatusResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StatusResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatusResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xtdb_protos.Service.StatusResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xtdb_protos_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xtdb_protos_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xtdb_protos_StatusResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xtdb_protos_StatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\013xtdb_protos\032\021transactio" +
      "n.proto\032\014entity.proto\"\007\n\005Empty\"\307\001\n\016Statu" +
      "sResponse\022\017\n\007version\030\001 \001(\t\022\025\n\rindex_vers" +
      "ion\030\002 \001(\005\022\020\n\010kv_store\030\003 \001(\t\022\031\n\021estimate_" +
      "num_keys\030\004 \001(\005\022\014\n\004size\030\005 \001(\003\022\025\n\010revision" +
      "\030\006 \001(\tH\000\210\001\001\022\033\n\016consumer_state\030\007 \001(\tH\001\210\001\001" +
      "B\013\n\t_revisionB\021\n\017_consumer_state2\360\002\n\007Grp" +
      "cApi\0229\n\006status\022\022.xtdb_protos.Empty\032\033.xtd" +
      "b_protos.StatusResponse\022A\n\006entity\022\032.xtdb" +
      "_protos.EntityRequest\032\033.xtdb_protos.Enti" +
      "tyResponse\022H\n\tentity_tx\022\034.xtdb_protos.En" +
      "tityTxRequest\032\035.xtdb_protos.EntityTxResp" +
      "onse\022W\n\016entity_history\022!.xtdb_protos.Ent" +
      "ityHistoryRequest\032\".xtdb_protos.EntityHi" +
      "storyResponse\022D\n\tsubmit_tx\022\032.xtdb_protos" +
      ".SubmitRequest\032\033.xtdb_protos.SubmitRespo" +
      "nseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xtdb_protos.TransactionOuterClass.getDescriptor(),
          xtdb_protos.Entity.getDescriptor(),
        });
    internal_static_xtdb_protos_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xtdb_protos_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xtdb_protos_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_xtdb_protos_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xtdb_protos_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xtdb_protos_StatusResponse_descriptor,
        new java.lang.String[] { "Version", "IndexVersion", "KvStore", "EstimateNumKeys", "Size", "Revision", "ConsumerState", "Revision", "ConsumerState", });
    xtdb_protos.TransactionOuterClass.getDescriptor();
    xtdb_protos.Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
